server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: ALWAYS

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: mcsv-usuarios

  datasource:
    url: jdbc:mariadb://40.233.27.238:3307/auth_db
    username: app_user
    password: appSa456.
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update   # En prod: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  kafka:
    admin:
      auto-create: true
    bootstrap-servers:
#      - localhost:9092
      - b-1.kafkap2sa.uqqw98.c10.kafka.us-east-1.amazonaws.com:9094
      - b-2.kafkap2sa.uqqw98.c10.kafka.us-east-1.amazonaws.com:9094
    consumer:
      group-id: usuarios-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        security.protocol: SSL
#        ssl.truststore.location: /app/truststore.jks
#        ssl.truststore.password: ${MSK_TRUSTSTORE_PASSWORD}
        ssl.endpoint.identification.algorithm: https
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        security.protocol: SSL
#        ssl.truststore.location: /app/truststore.jks
#        ssl.truststore.password: ${MSK_TRUSTSTORE_PASSWORD}
        ssl.endpoint.identification.algorithm: https

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret: vrksPUsAxyUzRIsbyisM2mYqlS1Ugvn8fanEC96HVuPIeHhpZyayi0nY/Aot+ZKG+hR3Iz1IPrAV1twvxn4ilw==
    expiration-seconds: 86400

logging:
  level:
    org.springframework.web: DEBUG
    org.apache.kafka: WARN

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8765/
      #defaultZone: http://localhost:8765/eureka/
    register-with-eureka: true
    fetch-registry: true

# <-- ESTA ES LA SECCIÓN CORRECTA (FUERA de 'spring')
app:
  frontend:
    base-url: http://40.233.27.238/auth/
  security:
    dev-return-token: true  
  kafka:
    enabled: true         # activa el publisher (ya no dirá “Kafka deshabilitado”)
    topic:
      users: users.events.v1
      reset-password: reset-user-password